# Generated by Django 2.2.8 on 2020-10-27 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposcontratos', '0001_initial'),
        ('monotributistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoMonotributista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monotributista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monotributistas.Monotributista')),
                ('tipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposcontratos.TipoContrato')),
            ],
            options={
                'verbose_name_plural': 'Contratos Monotributistas',
            },
        ),
    ]
