# Generated by Django 2.2 on 2020-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratomonotributistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomonotributista',
            name='decreto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contratomonotributista',
            name='expediente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
