# Generated by Django 2.2 on 2020-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratomonotributistas', '0002_auto_20201113_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomonotributista',
            name='cumplimentado',
            field=models.BooleanField(default=False),
        ),
    ]
