# Generated by Django 2.2 on 2020-11-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('cooperativas', '0002_auto_20201119_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.CharField(blank=True, max_length=250, null=True)),
                ('numeropoliza', models.CharField(blank=True, max_length=250, null=True)),
                ('tareas', models.CharField(blank=True, max_length=250, null=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.Contratista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.Obra')),
                ('tipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratocooperativas.TipoContrato')),
            ],
            options={
                'verbose_name_plural': 'Contratos de Obra',
            },
        ),
    ]
