# Generated by Django 2.2 on 2020-11-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('cooperativas', '0004_auto_20201119_1639'),
        ('contratocooperativas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratoObra',
            new_name='ContratoCooperativa',
        ),
    ]
