# Generated by Django 2.2 on 2020-11-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0002_auto_20201120_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocooperativa',
            name='tipocontrato',
        ),
    ]
