# Generated by Django 2.2 on 2020-11-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0003_remove_contratocooperativa_tipocontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoContrato',
        ),
    ]
