# Generated by Django 2.2 on 2020-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0004_delete_tipocontrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocooperativa',
            options={'verbose_name_plural': 'Contratos de Cooperativas'},
        ),
        migrations.RemoveField(
            model_name='contratocooperativa',
            name='obra',
        ),
        migrations.AddField(
            model_name='contratocooperativa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contratocooperativa',
            name='montomensual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='contratocooperativa',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
