# Generated by Django 2.2 on 2020-11-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0006_contratocooperativa_unidadtiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocooperativa',
            name='tareas',
        ),
    ]
