# Generated by Django 2.2 on 2020-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0008_auto_20201127_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocooperativa',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='contratocooperativa',
            name='unidadtiempo',
        ),
        migrations.AddField(
            model_name='contratocooperativa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratocooperativa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
