# Generated by Django 2.2 on 2020-11-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratocooperativas', '0009_auto_20201127_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocooperativa',
            name='cumplimentado',
            field=models.BooleanField(default=False),
        ),
    ]
