# Generated by Django 2.2.8 on 2020-11-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0005_contratista_cooperativa'),
        ('complementos', '0002_unidadtiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('poliza', models.CharField(blank=True, max_length=250, null=True)),
                ('numeropoliza', models.CharField(blank=True, max_length=250, null=True)),
                ('tareas', models.CharField(blank=True, max_length=250, null=True)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('montomensual', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.Contratista')),
                ('unidadtiempo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complementos.UnidadTiempo')),
            ],
            options={
                'verbose_name_plural': 'Contratos de Obras',
            },
        ),
    ]
