# Generated by Django 2.2.8 on 2020-11-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_auto_20201120_1457'),
        ('contratosobras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoobra',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.Obra'),
        ),
    ]
