# Generated by Django 2.2.8 on 2020-11-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratosobras', '0002_auto_20201122_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoobra',
            old_name='montomensual',
            new_name='monto',
        ),
    ]
