# Generated by Django 2.2.8 on 2020-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosobras', '0004_remove_contratoobra_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoobra',
            name='analisiprecio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='curvainversion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='fin_pliegogeneral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='fin_pliegoparticular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='fin_pliegotecnico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='inicio_pliegogeneral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='inicio_pliegoparticular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='inicio_pliegotecnico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='plano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoobra',
            name='plantrabajo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
