# Generated by Django 2.2.8 on 2020-11-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosobras', '0005_auto_20201122_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoobra',
            name='foja_decreto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
