# Generated by Django 2.2.8 on 2020-11-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosobras', '0006_contratoobra_foja_decreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoobra',
            name='montopoliza',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
