# Generated by Django 2.2 on 2020-11-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('domicilio', models.CharField(max_length=150)),
                ('titular', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contratistas',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionAdjunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentacion', models.FileField(upload_to='')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.Contratista')),
            ],
            options={
                'verbose_name_plural': 'Documentaciones Adjuntas',
            },
        ),
    ]
