# Generated by Django 2.2 on 2020-11-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='docrepresentantetecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='doctitular',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='contratista',
            name='representantetecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='titular',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
