# Generated by Django 2.2 on 2020-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0002_auto_20201119_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
