# Generated by Django 2.2 on 2020-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0003_auto_20201119_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
