# Generated by Django 2.2.8 on 2020-11-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativas', '0004_auto_20201119_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='cooperativa',
            field=models.BooleanField(default=False),
        ),
    ]
