# Generated by Django 2.2.8 on 2020-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monotributista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=70)),
                ('nombre', models.CharField(max_length=70)),
                ('numerodocumento', models.CharField(max_length=9)),
                ('cuit', models.CharField(max_length=11)),
                ('domicilio', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Monostributistas',
            },
        ),
    ]
