# Generated by Django 2.2.8 on 2020-10-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monotributistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monotributista',
            options={'verbose_name_plural': 'Monotributistas'},
        ),
    ]
