# Generated by Django 2.2.8 on 2020-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotributistas', '0002_auto_20201027_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monotributista',
            name='numerodocumento',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
