# Generated by Django 2.2 on 2020-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotributistas', '0003_auto_20201107_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monotributista',
            name='cuit',
            field=models.CharField(max_length=13),
        ),
    ]
