# Generated by Django 2.2 on 2020-12-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0005_contratista_cooperativa'),
        ('obras', '0004_auto_20201201_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expediente', models.CharField(max_length=10, unique=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.Contratista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.Obra')),
            ],
            options={
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
