# Generated by Django 2.2 on 2020-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='expediente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
