# Generated by Django 2.2 on 2020-11-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0002_auto_20201119_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Licitacion',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('expediente', models.CharField(max_length=15)),
                ('decreto', models.CharField(max_length=15)),
                ('numero_licitacion', models.CharField(blank=True, max_length=10, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.TipoLicitacion')),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Adjudicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoadjudicacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjudicatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.Contratista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.Obra')),
            ],
            options={
                'verbose_name_plural': 'Adjudicaciones',
            },
        ),
    ]
