# Generated by Django 2.2 on 2020-11-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complementos', '0002_unidadtiempo'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='unidadtiempo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complementos.UnidadTiempo'),
        ),
    ]
