# Generated by Django 2.2.8 on 2020-11-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_auto_20201120_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adjudicacion',
        ),
    ]
